version: "3.8"
services:
  prom:
    image: prom/prometheus:v2.33.4
    #networks:
      #- mon
    ports:
      - 9090:9090
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 4096M
        reservations:
          memory: 128M
    volumes:
      - ./prometheus/config:/etc/prometheus:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    command:
      - '--storage.tsdb.retention.time=30d'
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-admin-api'
      - '--web.enable-lifecycle'
      - '--enable-feature=remote-write-receiver'
    user: "0:0"

  grafana8:
    image: grafana/grafana:8.4.2-ubuntu
    ports:
      - 3000:3000   
    deploy:
      replicas: 1
      restart_policy:
        delay: 3s
        condition: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ./grafana/config/datasources:/etc/grafana/datasources
  
  node:
    image: prom/node-exporter:v1.0.1
    deploy:
      replicas: 1
      restart_policy:
        delay: 3s
        condition: on-failure
    volumes:
        - /proc:/host/proc:ro
        - /sys:/host/sys:ro
        - /:/rootfs:ro
    command:
        - '--path.procfs=/host/proc'
        - '--path.rootfs=/rootfs'
        - '--path.sysfs=/host/sys'
        - '--collector.filesystem.ignored-mount-points=^/(sys|proc|host|etc)($$|/)'
        - '--collector.textfile.directory=/home/'
        - '--no-collector.ipvs'
    ports:
        - "9100:9100"    
   


